# Generated by Django 5.2.17 on 2026-08-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 minutos'), (45, '45 minutos'), (60, '60 minutos')], default=30, verbose_name='duración en minutos'),
        ),
    ]
