# Generated by Django 5.2.17 on 2026-08-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_duracion_minutos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='cita_unica_por_veterinario_horario',
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('veterinario', 'fecha', 'hora'), name='cita_activa_unica_por_veterinario_horario'),
        ),
    ]
